# Generated by Django 3.1 on 2020-08-25 15:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burgers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('ingredients', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Τομάτα'), (2, 'Iceberg'), (3, 'Πίκλες')], max_length=5)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(upload_to='C:\\Users\\Tony\\Desktop\\sg_site\\src/static//pics')),
            ],
        ),
    ]
